/*
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.unicam.tryIde.parser.antlr.internal.InternalTryIdeParser;
import org.unicam.tryIde.services.TryIdeGrammarAccess;

public class TryIdeParser extends AbstractAntlrParser {

	@Inject
	private TryIdeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTryIdeParser createParser(XtextTokenStream stream) {
		return new InternalTryIdeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Solidity";
	}

	public TryIdeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TryIdeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
