/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arguments</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.Arguments#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getArguments()
 * @model
 * @generated
 */
public interface Arguments extends Qualifier
{
  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference.
   * @see #setArguments(FunctionCallArguments)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getArguments_Arguments()
   * @model containment="true"
   * @generated
   */
  FunctionCallArguments getArguments();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.Arguments#getArguments <em>Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arguments</em>' containment reference.
   * @see #getArguments()
   * @generated
   */
  void setArguments(FunctionCallArguments value);

} // Arguments
