/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends ContractOrLibrary
{
} // Contract
