/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Definition Optional Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getFunctionDefinitionOptionalElement()
 * @model
 * @generated
 */
public interface FunctionDefinitionOptionalElement extends EObject
{
} // FunctionDefinitionOptionalElement
