/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Library</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getLibrary()
 * @model
 * @generated
 */
public interface Library extends ContractOrLibrary
{
} // Library
