/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modifier Invocation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.ModifierInvocation#getName <em>Name</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.ModifierInvocation#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getModifierInvocation()
 * @model
 * @generated
 */
public interface ModifierInvocation extends FunctionDefinitionOptionalElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Modifier)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getModifierInvocation_Name()
   * @model
   * @generated
   */
  Modifier getName();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.ModifierInvocation#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Modifier value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(FunctionCallListArguments)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getModifierInvocation_Args()
   * @model containment="true"
   * @generated
   */
  FunctionCallListArguments getArgs();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.ModifierInvocation#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(FunctionCallListArguments value);

} // ModifierInvocation
