/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.tryGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shift</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.Shift#getLeft <em>Left</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.Shift#getShiftOp <em>Shift Op</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.tryGrammar.Shift#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getShift()
 * @model
 * @generated
 */
public interface Shift extends Expression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getShift_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.Shift#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Shift Op</b></em>' attribute.
   * The literals are from the enumeration {@link org.unicam.tryGrammar.tryGrammar.ShiftOpEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shift Op</em>' attribute.
   * @see org.unicam.tryGrammar.tryGrammar.ShiftOpEnum
   * @see #setShiftOp(ShiftOpEnum)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getShift_ShiftOp()
   * @model
   * @generated
   */
  ShiftOpEnum getShiftOp();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.Shift#getShiftOp <em>Shift Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shift Op</em>' attribute.
   * @see org.unicam.tryGrammar.tryGrammar.ShiftOpEnum
   * @see #getShiftOp()
   * @generated
   */
  void setShiftOp(ShiftOpEnum value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Expression)
   * @see org.unicam.tryGrammar.tryGrammar.TryGrammarPackage#getShift_Right()
   * @model containment="true"
   * @generated
   */
  Expression getRight();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.tryGrammar.Shift#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Expression value);

} // Shift
