/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar;

import org.unicam.tryGrammar.AbstractMyGrammarRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyGrammarRuntimeModule extends AbstractMyGrammarRuntimeModule {
}
