/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.unicam.tryIde.TryIdeRuntimeModule;
import org.unicam.tryIde.TryIdeStandaloneSetup;
import org.unicam.tryIde.ide.TryIdeIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TryIdeIdeSetup extends TryIdeStandaloneSetup {
  @Override
  public Injector createInjector() {
    TryIdeRuntimeModule _tryIdeRuntimeModule = new TryIdeRuntimeModule();
    TryIdeIdeModule _tryIdeIdeModule = new TryIdeIdeModule();
    return Guice.createInjector(Modules2.mixin(_tryIdeRuntimeModule, _tryIdeIdeModule));
  }
}
