/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.myGrammar.impl;

import org.eclipse.emf.ecore.EClass;

import org.unicam.tryGrammar.myGrammar.ConstantSpecifier;
import org.unicam.tryGrammar.myGrammar.MyGrammarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constant Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConstantSpecifierImpl extends VariableDeclarationOptionalElementImpl implements ConstantSpecifier
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstantSpecifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyGrammarPackage.eINSTANCE.getConstantSpecifier();
  }

} //ConstantSpecifierImpl
