/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Place Holder Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryIde.solidity.SolidityPackage#getPlaceHolderStatement()
 * @model
 * @generated
 */
public interface PlaceHolderStatement extends Statement
{
} // PlaceHolderStatement
