/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.myGrammar.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.unicam.tryGrammar.myGrammar.Expression;
import org.unicam.tryGrammar.myGrammar.MulDivMod;
import org.unicam.tryGrammar.myGrammar.MulDivModOpEnum;
import org.unicam.tryGrammar.myGrammar.MyGrammarPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mul Div Mod</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.impl.MulDivModImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.impl.MulDivModImpl#getMultipliciativeOp <em>Multipliciative Op</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.impl.MulDivModImpl#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MulDivModImpl extends ExpressionImpl implements MulDivMod
{
  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected Expression left;

  /**
   * The default value of the '{@link #getMultipliciativeOp() <em>Multipliciative Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultipliciativeOp()
   * @generated
   * @ordered
   */
  protected static final MulDivModOpEnum MULTIPLICIATIVE_OP_EDEFAULT = MulDivModOpEnum.MULT;

  /**
   * The cached value of the '{@link #getMultipliciativeOp() <em>Multipliciative Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultipliciativeOp()
   * @generated
   * @ordered
   */
  protected MulDivModOpEnum multipliciativeOp = MULTIPLICIATIVE_OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getRight() <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight()
   * @generated
   * @ordered
   */
  protected Expression right;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MulDivModImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyGrammarPackage.eINSTANCE.getMulDivMod();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeft(Expression newLeft, NotificationChain msgs)
  {
    Expression oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyGrammarPackage.MUL_DIV_MOD__LEFT, oldLeft, newLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLeft(Expression newLeft)
  {
    if (newLeft != left)
    {
      NotificationChain msgs = null;
      if (left != null)
        msgs = ((InternalEObject)left).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyGrammarPackage.MUL_DIV_MOD__LEFT, null, msgs);
      if (newLeft != null)
        msgs = ((InternalEObject)newLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyGrammarPackage.MUL_DIV_MOD__LEFT, null, msgs);
      msgs = basicSetLeft(newLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyGrammarPackage.MUL_DIV_MOD__LEFT, newLeft, newLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MulDivModOpEnum getMultipliciativeOp()
  {
    return multipliciativeOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMultipliciativeOp(MulDivModOpEnum newMultipliciativeOp)
  {
    MulDivModOpEnum oldMultipliciativeOp = multipliciativeOp;
    multipliciativeOp = newMultipliciativeOp == null ? MULTIPLICIATIVE_OP_EDEFAULT : newMultipliciativeOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyGrammarPackage.MUL_DIV_MOD__MULTIPLICIATIVE_OP, oldMultipliciativeOp, multipliciativeOp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getRight()
  {
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRight(Expression newRight, NotificationChain msgs)
  {
    Expression oldRight = right;
    right = newRight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyGrammarPackage.MUL_DIV_MOD__RIGHT, oldRight, newRight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRight(Expression newRight)
  {
    if (newRight != right)
    {
      NotificationChain msgs = null;
      if (right != null)
        msgs = ((InternalEObject)right).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyGrammarPackage.MUL_DIV_MOD__RIGHT, null, msgs);
      if (newRight != null)
        msgs = ((InternalEObject)newRight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyGrammarPackage.MUL_DIV_MOD__RIGHT, null, msgs);
      msgs = basicSetRight(newRight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyGrammarPackage.MUL_DIV_MOD__RIGHT, newRight, newRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyGrammarPackage.MUL_DIV_MOD__LEFT:
        return basicSetLeft(null, msgs);
      case MyGrammarPackage.MUL_DIV_MOD__RIGHT:
        return basicSetRight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyGrammarPackage.MUL_DIV_MOD__LEFT:
        return getLeft();
      case MyGrammarPackage.MUL_DIV_MOD__MULTIPLICIATIVE_OP:
        return getMultipliciativeOp();
      case MyGrammarPackage.MUL_DIV_MOD__RIGHT:
        return getRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyGrammarPackage.MUL_DIV_MOD__LEFT:
        setLeft((Expression)newValue);
        return;
      case MyGrammarPackage.MUL_DIV_MOD__MULTIPLICIATIVE_OP:
        setMultipliciativeOp((MulDivModOpEnum)newValue);
        return;
      case MyGrammarPackage.MUL_DIV_MOD__RIGHT:
        setRight((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyGrammarPackage.MUL_DIV_MOD__LEFT:
        setLeft((Expression)null);
        return;
      case MyGrammarPackage.MUL_DIV_MOD__MULTIPLICIATIVE_OP:
        setMultipliciativeOp(MULTIPLICIATIVE_OP_EDEFAULT);
        return;
      case MyGrammarPackage.MUL_DIV_MOD__RIGHT:
        setRight((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyGrammarPackage.MUL_DIV_MOD__LEFT:
        return left != null;
      case MyGrammarPackage.MUL_DIV_MOD__MULTIPLICIATIVE_OP:
        return multipliciativeOp != MULTIPLICIATIVE_OP_EDEFAULT;
      case MyGrammarPackage.MUL_DIV_MOD__RIGHT:
        return right != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (multipliciativeOp: ");
    result.append(multipliciativeOp);
    result.append(')');
    return result.toString();
  }

} //MulDivModImpl
