/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.myGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Break Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getBreakStatement()
 * @model
 * @generated
 */
public interface BreakStatement extends Statement
{
} // BreakStatement
