/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.myGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Parameter Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getFunctionParameterDeclaration()
 * @model
 * @generated
 */
public interface FunctionParameterDeclaration extends FunctionDeclaration
{
} // FunctionParameterDeclaration
