/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryGrammar.myGrammar;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Special Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.SpecialVariables#getType <em>Type</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.SpecialVariables#getField <em>Field</em>}</li>
 *   <li>{@link org.unicam.tryGrammar.myGrammar.SpecialVariables#getQualifiers <em>Qualifiers</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getSpecialVariables()
 * @model
 * @generated
 */
public interface SpecialVariables extends Literal
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(SpecialVariablesTypeEnum)
   * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getSpecialVariables_Type()
   * @model containment="true"
   * @generated
   */
  SpecialVariablesTypeEnum getType();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.myGrammar.SpecialVariables#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(SpecialVariablesTypeEnum value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' attribute.
   * @see #setField(String)
   * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getSpecialVariables_Field()
   * @model
   * @generated
   */
  String getField();

  /**
   * Sets the value of the '{@link org.unicam.tryGrammar.myGrammar.SpecialVariables#getField <em>Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' attribute.
   * @see #getField()
   * @generated
   */
  void setField(String value);

  /**
   * Returns the value of the '<em><b>Qualifiers</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.tryGrammar.myGrammar.Qualifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualifiers</em>' containment reference list.
   * @see org.unicam.tryGrammar.myGrammar.MyGrammarPackage#getSpecialVariables_Qualifiers()
   * @model containment="true"
   * @generated
   */
  EList<Qualifier> getQualifiers();

} // SpecialVariables
