/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elementary Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryIde.solidity.ElementaryType#getDimension <em>Dimension</em>}</li>
 *   <li>{@link org.unicam.tryIde.solidity.ElementaryType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryIde.solidity.SolidityPackage#getElementaryType()
 * @model
 * @generated
 */
public interface ElementaryType extends StandardType, StandardTypeWithoutQualifiedIdentifier
{
  /**
   * Returns the value of the '<em><b>Dimension</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimension</em>' containment reference.
   * @see #setDimension(ArrayDimensions)
   * @see org.unicam.tryIde.solidity.SolidityPackage#getElementaryType_Dimension()
   * @model containment="true"
   * @generated
   */
  ArrayDimensions getDimension();

  /**
   * Sets the value of the '{@link org.unicam.tryIde.solidity.ElementaryType#getDimension <em>Dimension</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dimension</em>' containment reference.
   * @see #getDimension()
   * @generated
   */
  void setDimension(ArrayDimensions value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.unicam.tryIde.solidity.ElementaryTypeNameEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see org.unicam.tryIde.solidity.ElementaryTypeNameEnum
   * @see #setName(ElementaryTypeNameEnum)
   * @see org.unicam.tryIde.solidity.SolidityPackage#getElementaryType_Name()
   * @model
   * @generated
   */
  ElementaryTypeNameEnum getName();

  /**
   * Sets the value of the '{@link org.unicam.tryIde.solidity.ElementaryType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see org.unicam.tryIde.solidity.ElementaryTypeNameEnum
   * @see #getName()
   * @generated
   */
  void setName(ElementaryTypeNameEnum value);

} // ElementaryType
