/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Indexed Specifer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryIde.solidity.SolidityPackage#getIndexedSpecifer()
 * @model
 * @generated
 */
public interface IndexedSpecifer extends VariableDeclarationOptionalElement
{
} // IndexedSpecifer
