/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.solidity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Now</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.tryIde.solidity.SolidityPackage#getNow()
 * @model
 * @generated
 */
public interface Now extends org.unicam.tryIde.solidity.Number
{
} // Now
