/**
 * generated by Xtext 2.19.0
 */
package org.unicam.tryIde.solidity;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Solidity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.tryIde.solidity.Solidity#getImportDirective <em>Import Directive</em>}</li>
 *   <li>{@link org.unicam.tryIde.solidity.Solidity#getContract <em>Contract</em>}</li>
 *   <li>{@link org.unicam.tryIde.solidity.Solidity#getLibrary <em>Library</em>}</li>
 * </ul>
 *
 * @see org.unicam.tryIde.solidity.SolidityPackage#getSolidity()
 * @model
 * @generated
 */
public interface Solidity extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Directive</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.tryIde.solidity.ImportDirective}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Directive</em>' containment reference list.
   * @see org.unicam.tryIde.solidity.SolidityPackage#getSolidity_ImportDirective()
   * @model containment="true"
   * @generated
   */
  EList<ImportDirective> getImportDirective();

  /**
   * Returns the value of the '<em><b>Contract</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.tryIde.solidity.Contract}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contract</em>' containment reference list.
   * @see org.unicam.tryIde.solidity.SolidityPackage#getSolidity_Contract()
   * @model containment="true"
   * @generated
   */
  EList<Contract> getContract();

  /**
   * Returns the value of the '<em><b>Library</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.tryIde.solidity.Library}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Library</em>' containment reference list.
   * @see org.unicam.tryIde.solidity.SolidityPackage#getSolidity_Library()
   * @model containment="true"
   * @generated
   */
  EList<Library> getLibrary();

} // Solidity
