/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Sub</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.myGrammar.optGrammar.AddSub#getLeft <em>Left</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.AddSub#getAdditionOp <em>Addition Op</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.AddSub#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getAddSub()
 * @model
 * @generated
 */
public interface AddSub extends Expression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getAddSub_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.AddSub#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Addition Op</b></em>' attribute.
   * The literals are from the enumeration {@link org.unicam.myGrammar.optGrammar.AdditionOpEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Addition Op</em>' attribute.
   * @see org.unicam.myGrammar.optGrammar.AdditionOpEnum
   * @see #setAdditionOp(AdditionOpEnum)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getAddSub_AdditionOp()
   * @model
   * @generated
   */
  AdditionOpEnum getAdditionOp();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.AddSub#getAdditionOp <em>Addition Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Addition Op</em>' attribute.
   * @see org.unicam.myGrammar.optGrammar.AdditionOpEnum
   * @see #getAdditionOp()
   * @generated
   */
  void setAdditionOp(AdditionOpEnum value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Expression)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getAddSub_Right()
   * @model containment="true"
   * @generated
   */
  Expression getRight();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.AddSub#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Expression value);

} // AddSub
