/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Definition Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getArrayDefinitionDeclaration()
 * @model
 * @generated
 */
public interface ArrayDefinitionDeclaration extends FunctionParameterDeclaration
{
} // ArrayDefinitionDeclaration
