/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends EObject
{
} // Declaration
