/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elementary Type Name Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getElementaryTypeNameEnum()
 * @model
 * @generated
 */
public interface ElementaryTypeNameEnum extends NamedType
{
} // ElementaryTypeNameEnum
