/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#isPayable <em>Payable</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getName <em>Name</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getOptionalElements <em>Optional Elements</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getReturnType <em>Return Type</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getBlocks <em>Blocks</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getReturnVal <em>Return Val</em>}</li>
 * </ul>
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition()
 * @model
 * @generated
 */
public interface FunctionDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Payable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payable</em>' attribute.
   * @see #setPayable(boolean)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_Payable()
   * @model
   * @generated
   */
  boolean isPayable();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#isPayable <em>Payable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payable</em>' attribute.
   * @see #isPayable()
   * @generated
   */
  void setPayable(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.myGrammar.optGrammar.FunctionParameterDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<FunctionParameterDeclaration> getParameters();

  /**
   * Returns the value of the '<em><b>Optional Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.myGrammar.optGrammar.FunctionDefinitionOptionalElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optional Elements</em>' containment reference list.
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_OptionalElements()
   * @model containment="true"
   * @generated
   */
  EList<FunctionDefinitionOptionalElement> getOptionalElements();

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(NamedType)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_ReturnType()
   * @model containment="true"
   * @generated
   */
  NamedType getReturnType();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(NamedType value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.myGrammar.optGrammar.InternalBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<InternalBlock> getBlocks();

  /**
   * Returns the value of the '<em><b>Return Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Val</em>' containment reference.
   * @see #setReturnVal(ReturnStatement)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getFunctionDefinition_ReturnVal()
   * @model containment="true"
   * @generated
   */
  ReturnStatement getReturnVal();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.FunctionDefinition#getReturnVal <em>Return Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Val</em>' containment reference.
   * @see #getReturnVal()
   * @generated
   */
  void setReturnVal(ReturnStatement value);

} // FunctionDefinition
