/**
 * generated by Xtext 2.20.0
 */
package org.unicam.myGrammar.optGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Indexed Specifer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getIndexedSpecifer()
 * @model
 * @generated
 */
public interface IndexedSpecifer extends VariableDeclarationOptionalElement
{
} // IndexedSpecifer
