/**
 * generated by Xtext 2.20.0
 */
package org.unicam.myGrammar.optGrammar;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mathematical Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.myGrammar.optGrammar.MathematicalFunction#getFunction <em>Function</em>}</li>
 *   <li>{@link org.unicam.myGrammar.optGrammar.MathematicalFunction#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getMathematicalFunction()
 * @model
 * @generated
 */
public interface MathematicalFunction extends Literal
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getMathematicalFunction_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.MathematicalFunction#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.unicam.myGrammar.optGrammar.IntParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getMathematicalFunction_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<IntParameter> getParameters();

} // MathematicalFunction
