/**
 * generated by Xtext 2.20.0
 */
package org.unicam.myGrammar.optGrammar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Now</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getNow()
 * @model
 * @generated
 */
public interface Now extends EObject
{
} // Now
