/**
 * generated by Xtext 2.19.0
 */
package org.unicam.myGrammar.optGrammar;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Visibility Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unicam.myGrammar.optGrammar.VisibilitySpecifier#getVisibility <em>Visibility</em>}</li>
 * </ul>
 *
 * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getVisibilitySpecifier()
 * @model
 * @generated
 */
public interface VisibilitySpecifier extends FunctionDefinitionOptionalElement, VariableDeclarationOptionalElement
{
  /**
   * Returns the value of the '<em><b>Visibility</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' containment reference.
   * @see #setVisibility(VisibilityEnum)
   * @see org.unicam.myGrammar.optGrammar.OptGrammarPackage#getVisibilitySpecifier_Visibility()
   * @model containment="true"
   * @generated
   */
  VisibilityEnum getVisibility();

  /**
   * Sets the value of the '{@link org.unicam.myGrammar.optGrammar.VisibilitySpecifier#getVisibility <em>Visibility</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibility</em>' containment reference.
   * @see #getVisibility()
   * @generated
   */
  void setVisibility(VisibilityEnum value);

} // VisibilitySpecifier
